version: '3'
services:
  helloworldapp:
    build: ./helloworld_app
    image: "helloworld:1.0"
    container_name: hello_world
    ports:
      - "3031:3030"

  nginx:
    build: ./nginx
    image: "custom_nginx:1.22.1"
    container_name: custom_nginx
    ports:
      - "81:80"
      - "444:443"
    restart: always
    network_mode: "host"
    depends_on:
      - helloworldapp

  mysql:
    image: "mysql:5.7"
    container_name: mysql
    environment:
      MYSQL_BATABASE: mydb
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql

# test
